services:
  apache:
    image: httpd:2.4
    ports:
      -"80:80"
    depends_on:
      - python
  
  python:
    build: .
    ports:
      -"5000:5000"
    depends_on:
      - basedatos
  
  basedatos:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD: 123
      - MYSQL_DATABASE: clicks
    ports:
      -"3306:3306"